### PR TITLE
Add padding to get Sidewinder 3D Pro Hat working in windows

### LINKED ISSUE #70: Sidewinder 3D Pro does not work in windows but in linux
The discussion started in #69, for me the Sidewinder 3D Pro works in linux but not in windows.
The FFB Wheel I have works in both systems with the same adapter and firmware.

Please hint me how to get proper debug information as I'm more a linux/embedded guy.

The device manager says

```
Device USB\VID_2341&PID_8037&MI_02\8&3153e260&0&0002 had a problem starting.

Driver Name: input.inf
Class Guid: {745a17a0-74d3-11d0-b6fe-00a0c90f57da}
Service: HidUsb
Lower Filters: 
Upper Filters: 
Problem: 0x0
Problem Status: 0xC00000E5
```

Sidewinder 3d Pro - 1

Sidewinder 3d Pro - 2

### PR DESCRIPTION
**Pull request by schuellerf**
Fixes #70 for my windows 7 and windows 11

### CODE REVIEW

**Comment by necroware** [comment]
Yeah, that confirms, that the issue is padding related. Pleas check out the branch, which I attached to the ticket, if that works for you.

**Comment by necroware** [comment]
This fix is not spec conform, but it is a step into right direction. The possible solution could be  https://github.com/necroware/gameport-adapter/tree/win10-usb-hid-fix

**Comment by rewk** [comment]
Hi,
I've made an integration of a Pico Pro inside of an old Sidewinder 3d pro. This commit was exactly the one that made it work on windows 10. It a bit specific case, because i don't need either dip switches or compatibility with other joysticks.
Thanks!

**Comment by schuellerf** [comment]
I was also thinking, if there is no generic solution and it seems off-spec to maybe add a dipsswitch like "sidewinder Windows", "sidewinder alternate protocol" or similar

**Pull request closed without merging**
