### PR TITLE
[Sidewinder 3D Pro] Change the powersupply of the gameport to VIN/RAW rather than VCC

### PR DESCRIPTION
**Pull request by schuellerf**
In my case with the Sidewinder 3D Pro, the joystick did not seem to run stable. Maybe there was too much power drawn from VCC?

Additionally it only works in linux and not in windows (whereas the Sidewinder FFB Wheel does work for linux and windows)
but that's obviously going to be a second issue...

I patched the power supply aside the board and it seems to work fine now but might not be fine for other joysticks.
Probably the PCB should be changed within this issue so there are two "solder-bridges" (or a jumper) and you can choose which powersupply to use. (I could also try to prepare this)

I'm a total noob when it comes to PCB design, so please check thoroughly!

### CODE REVIEW

**Comment by MacGH23** [comment]
Did you use the 5v or 3.3v Arduino version ?

**Comment by schuellerf** [comment]
Initially I started with the 3.3V version (which then worked) but I had similar problems with the 5v version.

**Comment by creopard** [comment]
Interesting find.

However, I've tested the current PCB layout with the current firmware version on various Sidewinder 3D Pros and can't reproduce this issue (on Windows 11 23H2).
The Sidewinders presumably have different production dates as their serial numbers imply (ranging from 0120XXX, 0396XXX, 0597XXX to 062XXX).

It's also strange that your build only works in Linux and not in Windows. If you patch the power supply it also works in Windows?
Which arduino model(s) did you use exactly?

**Comment by schuellerf** [comment]
My Sidewinder 3D Pro is a 0407XXX and I tested this and the FFB Wheel on two different Windows machines. Both detect the Wheel but not the 3D Pro. I'm an embedded and linux developer so I have no idea where to get windows-debug messages for this detection from. It just detects an unknown device... I can screenshot the hardware manager...

Since some days I finally received the PCBs and a logic analyzer, so I will to some re-testing now.

I have one
diymore Pro Micro ATMEGA32U4 5V 16MHz Development Board Type-C Interface Mikrocontroller (Upgraded Version) 
and two
1568-DEV-15795-ND SPARKFUN QWIIC PRO MICRO - USB-C
The links to the shop's are probably not well suited here - I can send them as a direct message if necessary.

**Comment by MacGH23** [comment]
I also tested with several 3DPro and never had any issue

**Comment by schuellerf** [comment]
The device Manager says
`Device USB\VID_2341&PID_8037&MI_02\8&3153e260&0&0002 had a problem starting.

Driver Name: input.inf
Class Guid: {745a17a0-74d3-11d0-b6fe-00a0c90f57da}
Service: HidUsb
Lower Filters: 
Upper Filters: 
Problem: 0x0


Problem Status: 0xC00000E5
`
Device Manager Sidewinder 3D Pro - 1

Device Manager Sidewinder 3D Pro - 2

**Comment by schuellerf** [comment]
> Hi! This shouldn't happen. Original Sidewinder 3D Pro doesn't need external powersupply and can be powered directly from the game port, which allows power draw of up to 50mA as far as I know. So the Sidewinder 3D Pro should not draw more than 50mA. As far as I know, the Arduino Pro Micro can draw maximum 200mA. The standard USB2 port provides at least 500mA, so plenty of current for the whole setup.
> 
> If the issue which you have is indeed power related, may be the USB ports on your windows machine are not able to keep the voltage steady. You can try to add 22µF capacitor between Vcc and Ground on your gameport adapter and see if something changes. If you think, there is a difference you can also try higher capacitor values. Lower values shouldn't make a difference, because there should already be some on the Arduino PCB for filtering purpose.

I totally agree! I'll do some more testing. Any hint how to debug the Windows detection issue (which obviously is now the wrong issue to discuss this)

**Comment by schuellerf** [comment]
I now re-solderd my VCC connection and it works (in linux - not in windows). Maybe I really was confused as I did start with a 3.3v version and obviously my second arduino board has some other issues not working at all....

Thanks ALOT for your quick responses and for the great project!
Should I move the "Windows detection" problem to a different issue and close this one? or rephrase the title?

**Comment by schuellerf** [comment]
Obviously I should move the windows problem to an issue as this is pullrequest 🙈

**Pull request closed without merging**
