### PR TITLE
Joystick-Adapter_9-15

### PR DESCRIPTION
**Pull request by Jo-Fri**
This is a 9 pin Kempston joystick to 15 pin PC GamePort joystick adapter, 
I have built this adapter already in 1993, but only now I made a KiCad plan afterwards.

Now you can play old games with an old Kemston joystick (from ZX-Spectrum / C64) via this adapter and your "USB GamePort adapter" under Windows / DOSBox.

Thank you for your "Arduino Pro Micro USB GamePort Adapter"

### CODE REVIEW

**Comment by necroware** [comment]
Thank you very much for sharing this. I think, this is also a great project and it definitely deserves an own repository, not just part of this one. Especially since it can be used separate for other projects as well.

**Comment by Jo-Fri** [comment]
I have created a new project:  https://github.com/Jo-Fri/gameport-adapter

**Comment by necroware** [comment]
Perfect! Very nice and thank you very much. Now people can use it in combination with other projects as well.

**Comment by Jo-Fri** [comment]
Hallo *


thank you very much

 


You can create a link to "Joystick-Adapter_9_to_15_Pin"   https://github.com/Jo-Fri/Joystick-Adapter_9_to_15_Pin

 

Viele Grüße
Josef

 
 

Gesendet: Samstag, 05. März 2022 um 18:02 Uhr
Von: "necroware" ***@***.***>
An: "necroware/gameport-adapter" ***@***.***>
Cc: "Jo-Fri" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [necroware/gameport-adapter] Joystick-Adapter_9-15 (PR #23)


 

Perfect! Very nice and thank you very much. Now people can use it in combination with other projects as well.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
